# Generated by Django 5.1.1 on 2024-09-11 11:56

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_invitation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from=["username", "first_name", "last_name"],
                unique=True,
            ),
        ),
    ]
