# Generated by Django 5.1.1 on 2024-09-11 12:05

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from=["position", "created_at"],
                unique=True,
            ),
        ),
    ]
