# Generated by Django 5.1.1 on 2024-09-11 13:45

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_invitation_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"], unique=True
            ),
        ),
    ]
