# Generated by Django 5.1.1 on 2024-09-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_team_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={"ordering": ("-created_at",)},
        ),
    ]
