# Generated by Django 5.1.1 on 2024-09-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_employee_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("name",)},
        ),
    ]
