# Generated by Django 5.1.1 on 2024-09-10 16:25

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                auto_created=True,
                blank=True,
                editable=False,
                populate_from=["name"],
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
