# Generated by Django 5.1.1 on 2024-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_invitation_options"),
        ("tasks", "0004_task_slug_alter_task_assignees_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("priority", "-deadline", "name")},
        ),
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(blank=True, to="employees.team"),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("1", "Urgent"), ("2", "High"), ("3", "Medium"), ("4", "Low")],
                max_length=100,
            ),
        ),
    ]
