# Generated by Django 5.1.1 on 2024-09-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_completed_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "priority", "-deadline", "name")},
        ),
    ]
